### PR TITLE
Edits with implementation details

### PR DESCRIPTION
**Pull request by chris-carney**

### CODE REVIEW

**Review by chris-carney — COMMENTED** [review]
Looks good to me

**Review by corysabol — CHANGES_REQUESTED** [review]
PR is backwards, trying to merge master into cmcarneybranch. Should be the other way around.

**Comment by chris-carney** [comment]
Yeah I thought the PR looked backwards. That's why I brought it up

**Comment by corysabol** [comment]
Let me do a little more work, It's telling me that your branch is the same as the master when I try and reverse it.

**Comment by chris-carney** [comment]
Sorry for causing so much trouble

**Comment by corysabol** [comment]
You're all good. It's a learning experience, my dude.

**Review by braggj5279 — COMMENTED** [review]
Looks okay to me. Most of the edits seem like spacing changes?

Nothing borked, at least nothing readily apparent.

**Comment by corysabol** [comment]
Closing this pull request as it is not needed. Everything is up to date on the master, it effectively contains all the work done by cmcarney.

**Pull request closed without merging**
